/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VBottomSheet: typeof import('vuetify/components')['VBottomSheet']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VChip: typeof import('vuetify/components')['VChip']
    VDialog: typeof import('vuetify/components')['VDialog']
    VDivider: typeof import('vuetify/components')['VDivider']
    VEmptyState: typeof import('vuetify/components')['VEmptyState']
    VFab: typeof import('vuetify/components')['VFab']
    VForm: typeof import('vuetify/components')['VForm']
    VIcon: typeof import('vuetify/components')['VIcon']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VListSubheader: typeof import('vuetify/components')['VListSubheader']
    VMenu: typeof import('vuetify/components')['VMenu']
    VSkeletonLoader: typeof import('vuetify/components')['VSkeletonLoader']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VSpeedDial: typeof import('vuetify/components')['VSpeedDial']
    VTextField: typeof import('vuetify/components')['VTextField']
  }
}
